USE PRATAP_EMPLOYEE
CREATE TABLE WORKERS
(
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(300) NOT NULL,
AGE INT  NOT NULL
)
INSERT INTO WORKERS(FNAME,LNAME,EMAIL,AGE)VALUES('SAI','PRATAP','SAIPRATAP017@GMAIL.COM',22);
INSERT INTO WORKERS(FNAME,LNAME,EMAIL,AGE)VALUES('VASU','DEVAVA','SUDEVA@GMAIL.COM',21);
INSERT INTO WORKERS(FNAME,LNAME,EMAIL,AGE)VALUES('LAKSHMI','NALINI','SAI017@GMAIL.COM',20)
ALTER TABLE WORKERS ADD CONSTRAINT checkage CHECK (AGE>=18)
ALTER TABLE WORKERS ADD CONSTRAINT uniquekey UNIQUE(EMAIL)
ALTER TABLE WORKERS ADD CONSTRAINT unique_FNAME_LNAME_key UNIQUE(FNAME,LNAME)
ALTER TABLE WORKERS ADD ID INT NOT NULL IDENTITY(501,1)
INSERT INTO WORKERS(FNAME,LNAME,EMAIL,AGE)VALUES('AK','NA','SAI017@GMAIL.COM',4)


SELECT * FROM WORKERS