USE PRATAP_EMPLOYEE
CREATE TABLE EMPLOYEES
(
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(300) NOT NULL,
AGE INT  NOT NULL
)
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE)VALUES('SAI','SAIPRATAP017@GMAIL.COM',22);
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE)VALUES('VASU','VASUDEVA@GMAIL.COM',21);
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE)VALUES('PRATAP','SAI017@GMAIL.COM',20)
--ADDING A COLUMN.BUT CANNOT ADD A NOT NULL COLUMN
ALTER TABLE EMPLOYEES ADD CITY VARCHAR(15) 
ALTER TABLE EMPLOYEES ADD STREET VARCHAR(15)
-- DELETING A COLUMN ALONG WITH THE DATA
--CHANGING THE SIZE OF THE COLUMN
ALTER TABLE EMPLOYEES ALTER COLUMN CITY VARCHAR(200)
-- CANNOT DO NULL VALUES TO NOT NULL
ALTER TABLE EMPLOYEES ALTER COLUMN CITY VARCHAR NOT NULL
ALTER TABLE EMPLOYEES DROP COLUMN CITY
--DROP(DELETE) THE TABLE ALONG WITH THE DATA
DROP TABLE EMPLOYEES
--ADDING A CONSTRAINT
ALTER TABLE EMPLOYEES ADD CONSTRAINT checkage CHECK (AGE>=18)
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE)VALUES('PRATAP','SAI@GMAIL.COM',8)
--DROP A CONSTRAINT
ALTER TABLE EMPLOYEES DROP CONSTRAINT checkage 
--DELETE THE DATA FROM THE TABLE BUT NOT THE COLUMN NAMES
DELETE FROM EMPLOYEES 
--UNIQUE CONSTRAINT.BUT IT CANNOT DO THE IF HAVE A DUPLICATE VALUES
ALTER TABLE EMPLOYEES ADD CONSTRAINT uniquekey UNIQUE(EMAIL)
--UNIQUE COMBINATION OF 2 COLUMNS.NAME AND AGE SHOULD BE DIFFERENT
ALTER TABLE EMPLOYEES ADD CONSTRAINT unique_FIRSTANME_key UNIQUE(NAME,AGE)
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE)VALUES('PRATAP','ADI@GMAIL.COM',8)
--DEFAULT CONSTRAINT.ALL ROWS WILL HAVE SAME VALUES
ALTER TABLE EMPLOYEES ADD CITY VARCHAR(100)NOT NULL DEFAULT 'ONGOLE'
--ADDING AN IDENTITY
ALTER TABLE EMPLOYEES ADD ID INT NOT NULL IDENTITY(501,1)
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE,CITY)VALUES('VIKRAM','VI@GMAIL.COM',28,'CHENNAI')
--BOTH SET IDENTITY_INSERT AND INSERT SHOULD BE EXECUTED AT THE SAME TIME
SET IDENTITY_INSERT EMPLOYEES ON
INSERT INTO EMPLOYEES(NAME,EMAIL,AGE,CITY,ID)VALUES('VIKRAMADHITYA','VIA@GMAIL.COM',28,'CHENNAI',506)
SELECT SUM(ID)AS AGESUM FROM EMPLOYEES

SELECT * FROM EMPLOYEES;

