CREATE TABLE LOG
(
ID INT PRIMARY KEY IDENTITY(1,1),
MESSAGE VARCHAR(100),
CREATEDDATE VARCHAR(100)
--OR CREATEDATE DATETIME
)
--CREATE TRIGGER TRCREATED
ALTER TRIGGER TRCREATED
ON CUSTOMERS
AFTER INSERT
AS BEGIN 
	DECLARE @CURRENTCUSTOMER INT=(SELECT ID FROM INSERTED)
	INSERT INTO LOG(MESSAGE,CREATEDDATE)VALUES('HAPPY BIRTHDAY'+CAST(@CURRENTCUSTOMER AS varchar),GETDATE())
END
INSERT INTO CUSTOMERS(NAME,ADDRESS)VALUES('AVINASH','ONGOLE')

SELECT * FROM LOG




ALTER TRIGGER TRPRODUCT
ON PRODUCTS
AFTER UPDATE
AS BEGIN 
	DECLARE @CURRENTPRODUCT  INT=(SELECT ID FROM INSERTED)


	INSERT INTO LOG(MESSAGE,CREATEDDATE)VALUES('UPDATE THE PRODUCT'+CAST(@CURRENTPRODUCT AS varchar),GETDATE())
	UPDATE PRODUCTS
	SET TOTAL_STOCK=100
	WHERE ID = @CURRENTPRODUCT AND TOTAL_STOCK = 0
	
END
UPDATE PRODUCTS
	SET TOTAL_STOCK=0
	WHERE ID=103;
SELECT * FROM LOG
SELECT * FROM PRODUCTS